{
 "title": "Docker Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Docker Containers State",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "docker_container_state", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "CPUs used by container (% CPUs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "docker_container_cpu_percent", "legendFormat": "{{name}}" },
    {}
   ]
  },
  {
   "title": "Total CPUs used vs Total CPUs available (% CPUs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "docker_total_cpu_used_percent", "legendFormat": "{{__name__}}" },
    {
     "expr": "docker_total_cpu_available_percent",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory used by container (in MegaBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "docker_container_memory_used_mb",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Memory used vs Total Memory available (in MegaBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "docker_total_memory_used_mb", "legendFormat": "{{__name__}}" },
    {
     "expr": "docker_total_memory_available_mb",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}